# Generated by Django 4.1.4 on 2022-12-21 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='permission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.role'),
        ),
    ]
