# Generated by Django 4.1.4 on 2022-12-21 08:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('admin', 'admin'), ('admin_assistant', 'admin assistant'), ('normal_user', 'normal user'), ('intermediate_user', 'intermediate user')], default='normal_user', max_length=20),
        ),
        migrations.AlterField(
            model_name='role',
            name='permission',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('[01]{7}', message='this permission is invalid')]),
        ),
    ]
