# Generated by Django 4.1.4 on 2022-12-22 07:57

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='permission',
            field=models.ForeignKey(default=accounts.models.Role.get_default_for_permission_user, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.role'),
        ),
    ]
