# Generated by Django 4.1.4 on 2022-12-21 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messengers', '0002_remove_message_file_filemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message', to='messengers.file'),
        ),
        migrations.DeleteModel(
            name='FileMessage',
        ),
    ]
